const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '..', 'src', 'i18n', 'en.js');
let content = fs.readFileSync(enPath, 'utf-8');

const dict = {
  '\n\n✅ 全部完成\n': '\n\n✅ All complete\n',
  '流式响应异常': 'Streaming response error',
  '模型配置': 'Model configuration',
  '未配置': 'Not configured',
  '网络错误': 'Network error',
  '【服务端错误】': '[Server Error]',
  '【模型配置错误】': '[Model Config Error]',
  '【网络错误】': '[Network Error]',
  '流式错误': 'Streaming error',
  '流式': 'Streaming',
  '默认正文': 'Default body',
  '重复修复版': 'Duplicate-fixed',
  '纲章矫正版': 'Outline-corrected',
  '风格矫正版': 'Style-corrected',
  '查看版本': 'View version',
  '章节 Fitness': 'Chapter Fitness',
  '系统日志': 'System logs',
  '清空': 'Clear',
  '最小化': 'Minimize',
  '暂无日志': 'No logs yet',
  '自动滚动中': 'Auto-scrolling',
  '已暂停自动滚动': 'Auto-scroll paused',
  '已连接': 'Connected',
  '连接中...': 'Connecting...',
  '多卷架构评审': 'Multi-volume review',
  '第1卷评审': 'Vol 1 review',
  '第2卷评审': 'Vol 2 review',
  '第3卷评审': 'Vol 3 review',
  '第4卷评审': 'Vol 4 review',
  '第5卷评审': 'Vol 5 review',
  'ReAct 评审记录': 'ReAct Review Records',
  '通过': 'Pass',
  '不通过': 'Fail',
  '已复制': 'Copied',
  '复制': 'Copy',
  '多Agent': 'Multi-Agent',
  '多卷': 'Multi-volume',
  '未命名作品': 'Untitled work',
  '暂无描述': 'No description',
  '删除作品': 'Delete work',
  '暂无内容': 'No content',
  '这里还没有任何内容': 'Nothing here yet',
  '还没有作品': 'No works yet',
  '主角': 'Protagonist',
  '反派': 'Antagonist',
  '配角': 'Supporting',
  '龙套': 'Extra',
  '存活': 'Alive',
  '死亡': 'Deceased',
  '失踪': 'Missing',
  '囚禁': 'Imprisoned',
  '飞升': 'Ascended',
  '师徒': 'Master-Apprentice',
  '敌对': 'Hostile',
  '恋人': 'Lover',
  '君臣': 'Lord-Subject',
  '血亲': 'Blood relative',
  '同盟': 'Ally',
  '主仆': 'Master-Servant',
  '竞争': 'Rival',
  '删除人物将同时删除其关联关系，确定？': 'Delete character and relations? Confirm?',
  '确定删除此关系？': 'Confirm delete this relationship?',
  '人物设定': 'Character settings',
  '加载中...': 'Loading...',
  '人物关系': 'Relationships',
  '强度': 'Intensity',
  '操作': 'Action',
  '编辑人物': 'Edit character',
  '新增人物': 'Add character',
  '姓名': 'Name',
  '别名': 'Alias',
  '外貌特征': 'Appearance',
  '性格特点': 'Personality',
  '背景故事...': 'Backstory...',
  '备注...': 'Notes...',
  '新增人物关系': 'Add relationship',
  '选择人物': 'Select character',
  '大陆': 'Continent',
  '国家': 'Nation',
  '城市': 'City',
  '宗门': 'Sect',
  '秘境': 'Secret realm',
  '山脉': 'Mountains',
  '河流': 'River',
  '村庄': 'Village',
  '道路': 'Road',
  '传送阵': 'Teleport',
  '敌对边界': 'Hostile border',
  '山脉隘口': 'Mountain pass',
  '确定删除此连接？': 'Confirm delete connection?',
  '地图图谱': 'Map atlas',
  '区域分布': 'Region distribution',
  '暂无区域': 'No regions yet',
  '区域连接': 'Region connections',
  '耗时': 'Duration',
  '编辑区域': 'Edit region',
  '新增区域': 'Add region',
  '区域名称': 'Region name',
  '无上级区域': 'No parent region',
  '区域描述...': 'Region description...',
  '新增区域连接': 'Add connection',
  '选择区域': 'Select region',
  '通行时间（如：3天）': 'Travel time (e.g. 3 days)',
  '连接描述...': 'Connection description...',
  '保存': 'Save',
  '取消': 'Cancel',
  '主线': 'Main plot',
  '支线': 'Side plot',
  '暗线': 'Hidden plot',
  '感情线': 'Romance',
  '起点': 'Start',
  '发展': 'Development',
  '高潮': 'Climax',
  '转折': 'Twist',
  '结局': 'Ending',
  '伏笔': 'Foreshadowing',
  '回收': 'Resolution',
  '进行中': 'In progress',
  '已完结': 'Completed',
  '待展开': 'Pending',
  '已发生': 'Occurred',
  '已回收': 'Resolved',
  '剧情线图谱': 'Plotline atlas',
  '未命名节点': 'Unnamed node',
  '暂无节点': 'No nodes yet',
  '添加节点': 'Add node',
  '编辑剧情线': 'Edit plotline',
  '新增剧情线': 'Add plotline',
  '剧情线名称': 'Plotline name',
  '编辑节点': 'Edit node',
  '新增节点': 'Add node',
  '节点标题': 'Node title',
  '章节号': 'Chapter #',
  '排序位置': 'Sort position',
  '套路模版': 'Story template',
  '已应用套路': 'Applied template',
  '从库中选择': 'Select from library',
  '力量体系': 'Power system',
  '历史事件': 'History',
  '地理区域': 'Geography',
  '世界观记忆库': 'Worldview library',
  '重要': 'Important',
  '分类': 'Category',
  '标题': 'Title',
  '（无返回）': '(No return)',
  '当前作品': 'Current work',
  '选择作品': 'Select work',
  '续写下一章': 'Continue next chapter',
  '请先选择作品': 'Please select a work first',
  '停止': 'Stop',
  '加载配置失败': 'Config load failed',
  '模型名称': 'Model name',
  '温度': 'Temperature',
  '无模板': 'No template',
  '隐藏系统提示': 'Hide system prompt',
  '编辑系统提示': 'Edit system prompt',
  '写下想法': 'Write thoughts',
  '选择风格': 'Select style',
  '退婚逆袭': 'Broken engagement',
  '系统觉醒': 'System awakening',
  '重生复仇': 'Rebirth revenge',
  '穿越古代': 'Time-travel ancient',
  '末日求生': 'Apocalypse survival',
  '修仙问道': 'Cultivation quest',
  '商战逆袭': 'Business comeback',
  '悬疑探案': 'Mystery detective',
  '甜宠恋爱': 'Sweet romance',
  '机甲战争': 'Mecha war',
  '快速模式': 'Fast mode',
  '1-2分钟': '1-2 min',
  '精品模式': 'Premium mode',
  '5-15分钟': '5-15 min',
  '工业风': 'Industrial',
  '严格量产': 'Strict production',
  '自由风': 'Free style',
  '创意探索': 'Creative exploration',
  '番茄': 'Fanqie',
  '热血磅礴': 'Hot-blooded',
  '创作完成！': 'Creation complete!',
  '导入成功！': 'Import success!',
  '导入失败:': 'Import failed:',
  '开始新创作': 'Start new creation',
  '发布平台': 'Publishing platform',
  '作者风格': 'Author style',
  '生成模式': 'Generation mode',
  '写作风格': 'Writing style',
  '无套路': 'No template',
  '自由创作': 'Free creation',
  '配置确认': 'Config confirm',
  '主题': 'Theme',
  '平台': 'Platform',
  '风格': 'Style',
  '模式': 'Mode',
  '写作': 'Writing',
  '套路': 'Template',
  '已选': 'Selected',
  '大纲模型': 'Outline model',
  '输入模型名': 'Enter model name',
  '正文模型': 'Body model',
  '润色模型': 'Polish model',
  '创作中...': 'Creating...',
  '错误': 'Error',
  '创作流程': 'Creation workflow',
  '导入已有作品': 'Import existing work',
  '小说标题': 'Novel title',
  '平台风格': 'Platform style',
  '完整正文': 'Full text',
  '导入中...': 'Importing...',
  '导入小说': 'Import novel',
  '开始拆书': 'Start deconstruction',
  '分析结果': 'Analysis results',
  '情节结构': 'Plot structure',
  '角色原型': 'Character archetypes',
  '文风指纹': 'Style fingerprint',
  '世界观规则': 'Worldview rules',
  '节奏模式': 'Pacing pattern',
  '可复用资源': 'Reusable resources',
  '历史记录': 'History',
  '未命名分析': 'Unnamed analysis',
  '已生成资源': 'Generated resources',
  '纯分析': 'Analysis only',
  '进化实验完成': 'Evolution complete',
  '错误:': 'Error:',
  '选择模板': 'Select template',
  '开始进化实验': 'Start evolution',
  '提升:': 'Improvement:',
  '否': 'No',
  '推荐应用:': 'Recommended:',
  '报告:': 'Report:',
  '诊断:': 'Diagnosis:',
  '改进方向:': 'Direction:',
  '系统概览': 'System overview',
  '系统设置详解': 'Settings details',
  '章节字数配置': 'Word count config',
  '创作辅助': 'Creation assistant',
  '套路模板库': 'Template library',
  '工具页面': 'Tools',
  '轮换写作': 'Rotation writing',
  '维度': 'Dimension',
  '创作规则': 'Creation rules',
  '8条严格规则': '8 strict rules',
  '大纲约束': 'Outline constraint',
  '字数控制': 'Word count control',
  '编辑轮数': 'Edit rounds',
  '最多 3 轮': 'Up to 3 rounds',
  '去AI化': 'De-AIization',
  '重度': 'Heavy',
  '轻度': 'Light',
  '适合场景': 'Use cases',
  '写作技能': 'Writing skills',
  '8 维精简版': '8-dimension concise',
  '评审维度': 'Review dimensions',
  '说明': 'Description',
  '任意名称': 'Any name',
  '轮换只影响': 'Rotation affects only',
  '用途': 'Usage',
  '建议温度': 'Recommended temperature',
  '校编': 'Proofreader',
  '润色': 'Polish',
  '读者反馈': 'Reader feedback',
  '摘要生成': 'Summary generation',
  '大纲生成': 'Outline generation',
  '偏离检测': 'Deviation detection',
  '风格修正': 'Style correction',
  '重复修复': 'Duplicate repair',
  '温度最佳实践': 'Temperature best practices',
  '自动注入': 'Auto-inject',
  '节拍结构': 'Beat structure',
  '代表作': 'Representative work',
  '标签': 'Tags',
  '不保存': 'Discard',
  '验证写作技能': 'Validate skills',
  '验证评审维度': 'Validate dimensions',
  '查看': 'View',
  '验证模型轮换': 'Validate rotation',
  '或查数据库：': 'Or check DB:',
  '记忆系统': 'Memory system',
  '刷新中...': 'Refreshing...',
  '刷新记忆': 'Refresh memory',
  '角色声纹指纹': 'Voice fingerprint',
  '平均句长': 'Avg sentence length',
  '对话占比': 'Dialogue ratio',
  '词汇丰富度': 'Vocabulary richness',
  '情感强度': 'Emotional intensity',
  '技能注入': 'Skill injection',
  '开篇钩子': 'Opening hook',
  '冲突升级': 'Conflict escalation',
  '余波回落': 'Aftermath decline',
  '结尾悬念': 'Ending cliffhanger',
  '节拍规划完成': 'Beat planning done',
  '章节节拍规划': 'Chapter beat plan',
  '作品': 'Work',
  '自动': 'Auto',
  '规划中...': 'Planning...',
  '生成节拍规划': 'Generate beat plan',
  '整体基调': 'Overall tone',
  '预计总字数': 'Estimated words',
  '风险提示': 'Risk alert',
  '加载失败:': 'Load failed:',
  '保存成功': 'Saved',
  '保存失败:': 'Save failed:',
  '切换失败:': 'Switch failed:',
  '配置加载失败': 'Config load failed',
  '章节配置': 'Chapter config',
  '流水线': 'Pipeline',
  '策划评审': 'Planning review',
  '通用评审': 'General review',
  '产品评审': 'Product review',
  '技术架构评审': 'Architecture review',
  '评审后修改': 'Post-review edit',
  '综合评审': 'Comprehensive review',
  '创作设置': 'Creation settings',
  '保存设置': 'Save settings',
  '失败': 'Failed',
  '当前评审预设': 'Current preset',
  '编辑评审维度': 'Edit dimensions',
  '新维度': 'New dimension',
  '添加维度': 'Add dimension',
  '维度名称': 'Dimension name',
  '评审描述': 'Review description',
  '删除': 'Delete',
  '作者风格预设': 'Author style preset',
  '新风格': 'New style',
  '添加风格': 'Add style',
  '风格名称': 'Style name',
  '平台风格预设': 'Platform preset',
  '新平台': 'New platform',
  '添加平台': 'Add platform',
  '平台名称': 'Platform name',
  '写作风格模式': 'Writing style mode',
  '模型库': 'Model library',
  '保存模型库': 'Save library',
  '添加模型库': 'Add library',
  '显示名称': 'Display name',
  '更新': 'Update',
  '添加': 'Add',
  '名称': 'Name',
  '模型数': 'Model count',
  '编辑': 'Edit',
  '自定义': 'Custom',
  '测试中...': 'Testing...',
  '测试': 'Test',
  '默认模型': 'Default model',
  '跟随默认': 'Follow default',
  '跟随角色默认': 'Follow role default',
  '已启用': 'Enabled',
  '未启用': 'Disabled',
  '选择模型': 'Select model',
  '添加模型': 'Add model',
  '目标字数': 'Target words',
  '允许最小字数': 'Allowed min words',
  '允许最大字数': 'Allowed max words',
  '绝对最小字数': 'Absolute min words',
  '绝对最大字数': 'Absolute max words',
  '生成初稿': 'Generate draft',
  '改稿审阅': 'Revision review',
  '模拟读者评审': 'Simulated reader review',
  '生成章节摘要': 'Generate summary',
  '最终润色': 'Final polish',
  '退婚流': 'Broken engagement',
  '系统流': 'System trope',
  '种田流': 'Farming trope',
  '夺宝流': 'Treasure hunt',
  '重生流': 'Rebirth trope',
  '签到流': 'Check-in trope',
  '凡人流': 'Commoner trope',
  '无敌流': 'Invincible trope',
  '后宫流': 'Harem trope',
  '新增模版': 'Add template',
  '编辑套路模版': 'Edit template',
  '新增套路模版': 'Add template',
  '模版名称': 'Template name',
  '编辑节拍': 'Edit beat',
  '新增节拍': 'Add beat',
  '预计章节数': 'Est. chapters',
  '作者': 'Author',
  '摘要': 'Summary',
  '策划': 'Planner',
  '上下文': 'Context',
  '未知': 'Unknown',
  '加载失败': 'Load failed',
  '查询': 'Query',
  '总调用次数': 'Total calls',
  '总耗时': 'Total time',
  '总输出字符': 'Total output chars',
  '调用时间线': 'Call timeline',
  '详细记录': 'Detailed records',
  '调用次数': 'Call count',
  '总字符': 'Total chars',
  '平均耗时': 'Avg duration',
  '暂无详细记录': 'No records yet',
  '生成简介大纲': 'Gen brief outline',
  '生成详细纲章': 'Gen detailed outline',
  '续写第一卷': 'Continue vol 1',
  '生成失败': 'Generation failed',
  '创作模式': 'Creation mode',
  '已完成': 'Completed',
  '生成中...': 'Generating...',
  '生成中': 'Generating',
  '重新生成': 'Regenerate',
  '生成': 'Generate',
  '核心创作': 'Core creation',
  '概览': 'Overview',
  '世界观': 'Worldview',
  '人物': 'Characters',
  '地图': 'Map',
  '数据分析': 'Data analysis',
  '评审记录': 'Review records',
  '作品已删除': 'Work deleted',
  '删除失败:': 'Delete failed:',
  '续写完成': 'Continuation done',
  '刷新': 'Refresh',
  '作品详情': 'Work details',
  '默认风格': 'Default style',
  '续写中...': 'Continuing...',
  '总章节': 'Total chapters',
  '总字数': 'Total words',
  '写作模式': 'Writing mode',
  '简介大纲': 'Brief outline',
  '暂无简介大纲': 'No brief outline',
  '详细纲章': 'Detailed outline',
  '暂无详细纲章': 'No detailed outline',
  '章节内容': 'Chapter content',
  '暂无章节': 'No chapters',
  '未命名章节': 'Unnamed chapter',
  '正文预览': 'Body preview',
  '钩子': 'Hook',
  '升级': 'Escalation',
  '回落': 'Decline',
  '悬念': 'Cliffhanger',
  '确定移除此套路？': 'Confirm remove template?',
  '尚未应用任何套路': 'No template applied',
  '系统提示词（可选）。选择 Prompt 模板后会自动加载模板内容，也可以在此手动覆盖。': 'System prompt (optional). Template content auto-loads on selection, or override manually.',
  '【模型配置错误】请前往「设置 → 模型配置」检查 Provider、Base URL、API Key 和模型名称是否正确。': '[Model Config Error] Go to "Settings → Model Config" to check Provider, Base URL, API Key and model name.',
  '【网络错误】无法连接到模型服务，请检查 Base URL 是否正确、服务是否运行。': '[Network Error] Cannot connect to model service. Check Base URL and service status.',
  '基于历史作品的 Fitness 数据，自动诊断 Prompt 缺陷并生成改进变体。': 'Based on historical Fitness data, auto-diagnose Prompt defects and generate improved variants.',
  '>严格（目标 ± 区间）': '>Strict (target ± range)',
  'Fitness 字数权重': 'Fitness word weight',
  '同时影响：Prompt 字数变量、Fitness 字数得分、导入切分策略。': 'Also affects: Prompt word variable, Fitness word score, import split strategy.',
  'OpenAI 兼容 API': 'OpenAI-compatible API',
  '所有模型均通过 OpenAI 兼容协议调用，配置 baseURL 和 API Key 即可': 'All models use OpenAI-compatible protocol, configure baseURL and API Key',
  'editor 审阅修改': 'Editor review',
  'humanizer 风格化': 'Humanizer stylization',
  'proofreader 校对': 'Proofreader proofreading',
  'summarizer 摘要': 'Summarizer summary',
  '：记录力量体系、势力分布、历史背景、特殊规则。支持分类、标签、重要性标记。': ': Records power systems, force distribution, history, special rules. Supports categories, tags, importance.',
  '系统内置 5 种经典网文套路：退婚流、系统流、种田流、凡人流、签到流。每种包含：': '5 classic web novel templates built-in. Each contains:',
  '适合快速测试 Prompt、调试模型输出。对话内容': 'For quick Prompt testing and debugging model output. Dialogue',
  '进入「设置 → 技能」，在 skill 开头加一句明显的话，如': 'Go to "Settings → Skills", add an obvious sentence at skill start, e.g.',
  '「设置 → 模型配置」→ 启用轮换 → 配置至少 2 个不同模型 → 保存': '"Settings → Model Config" → Enable rotation → Configure 2+ models → Save',
  '粘贴小说正文，系统': 'Paste novel text, system',
  '按章节切分': 'splits by chapter',
  '故事模板已': 'Story template',
  '声纹已提取': 'voice fingerprint extracted',
  '连续写两章 → 观察前端步骤进度条中的': 'Write 2 chapters → observe model names in progress bar',
  '名是': 'name is',
  '不同': 'different',
  '在「': 'In "',
  '中': '"',
  '设定和': 'settings and',
  '确认 Prompt 末尾包含「': 'Confirm Prompt end contains "',
  '区块': 'block"',
  '闭环、符合': 'closed loop, matching',
  '调性。': 'tone.',
  '视角': 'perspective',
  '：表达、共情与生命力。真诚比技巧': ': expression, empathy, vitality. Sincerity over technique',
  '、独特的声音、让': ', unique voice, let',
  '自己活下去、细节即真实、写你想读的书。': 'live on their own, details are truth, write what you want to read.',
  '算法视角': 'algorithm perspective',
  '：数据、留存与分发。完读率第一、追更率决定天花板、': ': data, retention, distribution. Completion rate first, follow rate ceiling,',
  '匹配、互动数据放大、适配滑动习惯。': 'matching, interaction amplification, swipe-friendly.',
  '暂无声纹数据。继续创作章节后，系统会': 'No voice data yet. After creating chapters, system will',
  '提取。': 'extract.',
  '记忆。系统会在章节总结后': 'memory. System will after chapter summary',
  '基于高评分章节': 'Based on high-scoring chapters',
  '提取的': 'extracted',
  '技巧，已注入到后续章节的创作提示中。': 'skills, injected into subsequent creation prompts.',
  '会被注入到所有': 'will be injected into all',
  '的 Prompt 中，作为硬性创作规范。': 'Prompts as hard creation rules.',
  '选择系统': 'Select system',
  '的': '\'s',
  '。创建': '. Create',
  '时可单独覆盖。': 'can be overridden individually.',
  '必须严格遵循': 'must be strictly followed',
  '最多3轮严格评审': 'up to 3 rounds strict review',
  '为参考，允许偏离和即兴': 'as reference, deviation allowed',
  '适合：灵感驱动、探索性': 'Suitable for: inspiration-driven, exploratory',
  '成功：': 'Success:',
  '可用': 'Available',
  '批量设置（勾选下方': 'Batch setting (check',
  '后应用）': 'then apply)',
  '跟随 Provider': 'Follow Provider',
  '分配': 'assignment',
  '高级选项：作家轮换': 'Advanced: writer rotation',
  '暂无轮换': 'No rotation',
  '，点击「': ', click "',
  '」开始配置。': '" to configure.',
  '点击上方按钮': 'Click button above',
  '渐进式体验': 'Progressive experience',
  '，每一步都可以预览效果后再决定下一步': ', preview each step before next',
  '小说': 'Novel',
  ' / 一句话灵感': ' / One-sentence inspiration',
  '点击「': 'Click "',
  '后，': 'after,',
  '将在这里实时': 'will stream here',
  '输出...': 'output...',
  '点击': 'Click',
  '详情、续写或管理': 'for details, continue or manage',
  '未获取到节拍规划（Plan 模式可能已关闭）': 'No beat plan retrieved (Plan mode may be off)',
};

// Replace in en.js: match ': 'value',' pattern exactly
for (const [cn, en] of Object.entries(dict)) {
  const escaped = cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`(: ')${escaped}('[,;])`, 'g');
  content = content.replace(re, `$1${en.replace(/'/g, "\\'")}$2`);
}

fs.writeFileSync(enPath, content, 'utf-8');
console.log('Translated en.js');
