const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '..', 'src', 'i18n', 'en.js');
let content = fs.readFileSync(enPath, 'utf-8');

const dict = {
  '✅ 全部完成': '✅ All complete',
  '中文': 'Chinese',
  '默认': 'Default',
  '其他': 'Other',
  '关系': 'Relationship',
  '连接': 'Connection',
  '区域': 'Region',
  '类型': 'Type',
  '确定删除此节点？': 'Confirm delete this node?',
  '剧情线': 'Plotline',
  '节点描述...': 'Node description...',
  '确定删除此条目？': 'Confirm delete this entry?',
  '编辑世界观条目': 'Edit worldview entry',
  '新增世界观条目': 'Add worldview entry',
  '内容': 'Content',
  '详细描述...': 'Detailed description...',
  '修仙, 灵根, 境界': 'Cultivation, Spirit Root, Realm',
  '对话式创作 Agent': 'Conversational Creation Agent',
  '把主角的性格改得更冷酷一些': 'Make the protagonist colder',
  '给第三章增加一个反转': 'Add a twist to Chapter 3',
  '请先选择一部作品': 'Please select a work first',
  'Agent 执行了以下操作：': 'Agent performed the following:',
  '输入命令...': 'Enter command...',
  '模型': 'Model',
  '输入消息，按 Enter 发送，Shift+Enter 换行': 'Type message, Enter to send, Shift+Enter for newline',
  '开始创作': 'Start creating',
  '适合试水和短篇': 'For quick tests and short stories',
  '8条规则、3轮编辑、重度去AI': '8 rules, 3 edit rounds, heavy de-AI',
  '2条底线、1轮轻量、轻度去AI': '2 baselines, 1 light round, light de-AI',
  '请先输入小说主题': 'Please enter a novel theme',
  '请填写标题和正文': 'Please fill in title and body',
  '3步完成，AI 帮你把想法变成小说': '3 steps, AI turns ideas into novels',
  '今天想写什么故事？': 'What story today?',
  'AI 正在创作中...': 'AI is creating...',
  '拆书分析': 'Deconstruct Analysis',
  '支持 .txt / .md，建议 3-30 万字': 'Supports .txt/.md, 30k-300k words',
  '在此粘贴小说正文...': 'Paste novel text here...',
  'Prompt 自动进化': 'Prompt Auto-Evolution',
  '快速开始：3步写小说': 'Quick start: 3-step novel writing',
  '工业风 vs 自由风': 'Industrial vs Free style',
  '如何验证功能是否生效': 'How to verify features',
  'knowrite 小说创作工作台': 'knowrite Novel Writing Studio',
  '让每个 Agent 只干一件事': 'Each Agent does one thing',
  '策划（Planner）': 'Planner',
  '：根据主题生成大纲': ': Generate outline from theme',
  '作者（Writer）': 'Writer',
  '：按大纲撰写章节初稿': ': Draft chapters from outline',
  '编辑（Editor）': 'Editor',
  '：按评审维度审查并给出修改意见': ': Review by dimensions and suggest edits',
  '去AI化（Humanizer）': 'De-AIizer',
  '：消除 AI 腔调，增加人味': ': Remove AI tone, add humanity',
  '校编（Proofreader）': 'Proofreader',
  '读者（Reader）': 'Reader',
  '：从读者视角给出可读性评分和反馈': ': Reader perspective readability score & feedback',
  '摘要（Summarizer）': 'Summarizer',
  'Step 1：写下你的想法': 'Step 1: Write your idea',
  'Step 2：选择风格': 'Step 2: Choose style',
  '：番茄、起点、晋江、七猫、飞卢等 10 个平台': ': Fanqie, Qidian, Jinjiang, etc. 10 platforms',
  '：热血磅礴、少年逆袭、体系严谨、深情宿命等 80 种风格': ': Hot-blooded, comeback, rigorous, etc. 80 styles',
  '：快速模式（1-2分钟）或精品模式（5-15分钟，多轮精修）': ': Fast (1-2min) or Premium (5-15min, multi-round)',
  '：工业风（严格量产）或自由风（创意探索）': ': Industrial (strict) or Free (creative)',
  'Step 3：开始创作': 'Step 3: Start creating',
  '建议性（约 X 字）': 'Suggested (approx X words)',
  '仅 1 轮轻量检查': 'Only 1 light check round',
  '设置页共 7 个 Tab，每个都影响创作行为的某个方面。': 'Settings has 7 tabs, each affects creation behavior.',
  '15 维标准版': '15-dimension standard',
  '33 维完整版': '33-dimension full',
  '控制每章的目标字数和容忍区间：': 'Control target word count and tolerance:',
  '：目标字数（默认 2000）': ': Target words (default 2000)',
  '：常规容忍区间（1800-2200）': ': Normal tolerance (1800-2200)',
  '：绝对硬边界（1600-2500）': ': Absolute hard limit (1600-2500)',
  '决定每个 Agent 用什么模型、什么温度生成内容。': 'Decide which model & temperature for each Agent.',
  'Provider 配置': 'Provider Config',
  '第 1 章 → 列表第 1 个模型': 'Ch 1 → Model 1 in list',
  '第 2 章 → 列表第 2 个模型': 'Ch 2 → Model 2 in list',
  '第 N 章 →': 'Ch N →',
  '(N-1) % 模型数量': '(N-1) % model count',
  'writer（作者）': 'writer (author)',
  '角色默认模型与温度': 'Role default model & temperature',
  '角色': 'Role',
  'polish 润色': 'polish',
  'reader 评分': 'reader scoring',
  'outline 大纲': 'outline',
  'Fitness评估': 'Fitness evaluation',
  '创作辅助：世界观、人物、剧情线、地图': 'Assist: worldview, characters, plotlines, maps',
  '：方便检索和分类': ': For search & classification',
  '选择任意 Provider 和模型': 'Select any Provider and model',
  '加载任意 Prompt 模板作为系统提示': 'Load any Prompt template as system prompt',
  '多轮对话，SSE 流式输出': 'Multi-turn dialogue, SSE streaming',
  '温度调节（0~2）': 'Temperature (0~2)',
  '，刷新即丢失。': ', lost on refresh.',
  '，搜索「测试标记」': ', search "test marker"',
  '切换评审预设（8/15/33 维）→ 写一章': 'Switch review preset (8/15/33 dims) → write chapter',
  '，确认维度数量与预设一致': ', confirm dimension count matches preset',
  '验证创作辅助注入': 'Verify creation assistant injection',
  '从已写章节中自动提取的各角色语言风格统计。': 'Auto-extracted character language style stats.',
  '角色 episodic 记忆': 'Character episodic memory',
  '正在生成本章节拍规划...': 'Generating chapter beat plan...',
  '流水线配置保存成功': 'Pipeline config saved',
  '流水线配置保存失败:': 'Pipeline save failed:',
  '模型库保存成功': 'Model library saved',
  '模型库保存失败:': 'Model library save failed:',
  '新Provider': 'New Provider',
  '已应用最佳实践温度': 'Applied best-practice temperature',
  '写作技能 (Skill)': 'Writing skills (Skill)',
  '精简版 · 8维度': 'Concise · 8 dimensions',
  '标准版 · 15维度': 'Standard · 15 dimensions',
  '完整版 · 33维度': 'Full · 33 dimensions',
  '切换预设中...': 'Switching preset...',
  'Prompt进化': 'Prompt Evolution',
  '核心写作规则 (core-rules)': 'Core writing rules (core-rules)',
  '描述': 'Description',
  '风格展开描述，会注入到 Prompt 中': 'Style description, injected into Prompt',
  '平台风格展开描述': 'Platform style description',
  '• 重度去AI化 + 全量ReAct评审': '• Heavy de-AI + full ReAct review',
  '• 适合：商业化量产、IP开发': '• For: commercial mass production, IP dev',
  '• 只保留2条底线（吸引力+人物一致性）': '• Only 2 baselines (appeal + character consistency)',
  '• 编辑1轮轻量检查': '• Editor 1 light round',
  '• 轻度去AI化，跳过proofreader': '• Light de-AI, skip proofreader',
  'Key (唯一标识)': 'Key (unique ID)',
  '模型列表，每行一个，格式：id|名称（如 qwen-plus|Qwen-Plus）': 'Model list, one per line, format: id|name',
  '添加 Provider': 'Add Provider',
  '从模型库选择…': 'Select from library...',
  'API Key（本地模型可留空）': 'API Key (local models can leave blank)',
  '使用第一个可用模型': 'Use first available model',
  '输入模型 ID（如 qwen3:4b）': 'Enter model ID (e.g. qwen3:4b)',
  '暂无 Provider，点击「添加 Provider」开始配置。可从上方模型库快速选择。': 'No Provider yet, click "Add Provider" to configure.',
  '-- 未设置 --': '-- Not set --',
  '角色未指定 Provider 时将使用默认 Provider': 'Role without Provider uses default',
  '应用最佳实践温度': 'Apply best-practice temperature',
  '从角色默认同步': 'Sync from role default',
  '这些配置会同时影响 Prompt 模板中的字数要求和 Fitness 评估的目标字数。': 'These affect Prompt word count & Fitness target.',
  'Prompt 中要求 AI 写作的目标字数': 'Target word count in Prompt',
  'Prompt 中禁止低于的字数（硬下限）': 'Hard minimum word count in Prompt',
  '写作流水线配置': 'Writing pipeline config',
  '控制续写时各 Agent 阶段的启用/禁用状态，以及 Plan 预演模式。': 'Control Agent stage toggle & Plan preview mode.',
  '保存流水线配置': 'Save pipeline config',
  'Plan 预演模式': 'Plan preview mode',
  '续写前先生成章节节拍规划，作者确认后再执行 Writer': 'Generate beat plan before continuing, confirm then Writer',
  '降低 AI 痕迹': 'Reduce AI traces',
  '校对语法和逻辑': 'Proofread grammar & logic',
  '润色（Polish）': 'Polish',
  '确定删除此套路模版？': 'Confirm delete this template?',
  '套路模版库': 'Story template library',
  '套路描述...': 'Template description...',
  '大纲': 'Outline',
  'Trace 调试台': 'Trace Debug',
  '或输入 workId': 'Or enter workId',
  'works/xxx 或 xxx': 'works/xxx or xxx',
  '暂无 trace 数据': 'No trace data yet',
  '暂无时间线数据': 'No timeline data yet',
  '创作正文前3章，体验实际写作风格和人物表现': 'Create first 3 chapters, experience writing style',
  '1-2分钟，适合试水和短篇': '1-2 min, for quick tests & shorts',
  '5-15分钟，质量更高，多轮精修': '5-15 min, higher quality, multi-round polish',
  '尝试创作': 'Try Creating',
  '正在续写下一章...': 'Continuing next chapter...',
  '我的作品': 'My Works',
  '... (内容过长已截断，请导出查看完整内容) ...': '... (content truncated, export to view full) ...',
};

for (const [cn, en] of Object.entries(dict)) {
  const esc = cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`(:\\s*')${esc}('[,;])`, 'g');
  content = content.replace(re, `$1${en.replace(/'/g, "\\'")}$2`);
}

fs.writeFileSync(enPath, content, 'utf-8');
console.log('Translated', Object.keys(dict).length, 'entries');
